language: php

sudo: required

services:
  - rabbitmq

php:
 - 7.0
 - 7.1
 - 7.2

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
 - composer update $PREFER_LOWEST

script:
 - ./vendor/bin/phpunit

after_script:
 - ./vendor/bin/coveralls -v
